/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ChatSection: typeof import('./components/ChatSection.vue')['default']
    InputSection: typeof import('./components/InputSection.vue')['default']
  }
}
